### ISSUE TITLE
1KG.chr22.anno.infocol.vcf.gz has a malformed header according to htsjdk

### ISSUE THREAD

**Issue by heuermh** [Steven-N-Hart/VariantDB_Challenge#3]
It appears that 1KG.chr22.anno.infocol.vcf.gz uses VCF v4.2 style `##INFO` header lines while reporting it is in VCF v4.0 format (`##fileformat=VCFv4.0`).

Compare
http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40
 and
http://samtools.github.io/hts-specs/VCFv4.2.pdf

``` bash
$ adam-submit vcf2adam 1KG.chr22.anno.infocol.vcf 1KG.chr22.anno.infocol.adam
2016-03-08 10:49:54 ERROR Executor:95 - Exception in task 0.0 in stage 0.0 (TID 0)
htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header:
unexpected tag count 6 in line <ID=ENST,Number=.,Type=String,Description="Ensembl transcript identifier",Source="savant",Version="1.1.0">
    at htsjdk.variant.vcf.VCF4Parser.parseLine(VCFHeaderLineTranslator.java:109)
    at htsjdk.variant.vcf.VCFHeaderLineTranslator.parseLine(VCFHeaderLineTranslator.java:51)
    at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:164)
    at htsjdk.variant.vcf.VCFInfoHeaderLine.<init>(VCFInfoHeaderLine.java:48)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:199)
    at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
    at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
    at org.seqdoop.hadoop_bam.VCFRecordReader.initialize(VCFRecordReader.java:87)
    at org.seqdoop.hadoop_bam.VCFInputFormat.createRecordReader(VCFInputFormat.java:189)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:149)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:122)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:63)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by heuermh** [comment]
More VCF format errors

```
Caused by: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 249: The VCF specification does not allow for whitespace in the INFO field. Offending field value was "DP=1710;AF=0.006;CB=BC,NCBI;Effect_Impact=MODIFIER;Genotype_Number=1;TYPE=SNP;ENST=.;GENE=.;Link_GeneCards=<a href="http://www.genecards.org/cgi-bin/carddisp.pl?gene=." target="_blank">.</a>;INFO=.;LOC=.;HGVS=.;CLASS=.;ALTANN=.;Link_GoogleSearch=<a href="https://www.google.com/search?q=.+.+p" target="_blank">Google It!</a>;Link_IGV=<a href="http://localhost:60151/goto?locus=22:16861344">View in IGV</a>"
    at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:780)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseInfo(AbstractVCFCodec.java:406)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:321)
    at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:279)
    at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
    at org.seqdoop.hadoop_bam.VCFRecordReader.nextKeyValue(VCFRecordReader.java:133)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:161)
    at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1111)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1119)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1091)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

```
Caused by: java.lang.NumberFormatException: For input string: "."
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at htsjdk.variant.variantcontext.GenotypeLikelihoods.parseDeprecatedGLString(GenotypeLikelihoods.java:251)
    at htsjdk.variant.variantcontext.GenotypeLikelihoods.fromGLField(GenotypeLikelihoods.java:81)
    at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:715)
    at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:128)
    at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
    at htsjdk.variant.variantcontext.LazyGenotypesContext.getGenotypes(LazyGenotypesContext.java:148)
    at htsjdk.variant.variantcontext.GenotypesContext.iterator(GenotypesContext.java:465)
    at scala.collection.convert.Wrappers$JListWrapper.iterator(Wrappers.scala:87)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.bdgenomics.adam.converters.VariantContextConverter.extractGenotypes(VariantContextConverter.scala:258)
```

**Comment by Steven-N-Hart** [comment]
What version of VCF-validator are you using so I can reproduce this locally?

**Comment by heuermh** [comment]
Any recent version of Picard should give similar stack traces, we're using htsjdk transitively through other dependencies.  I'm still trying to suss out who is the responsible party for each of these.  :)

**Comment by heuermh** [comment]
With the following reformatting, `1KG.chr22.anno.infocol.edit.vcf` makes it through our VCF &rarr; ADAM step

``` bash
$ sed -e 's/,Source="savant",Version="1.1.0"//' \
      -e 's/ /%20/g' \
      -e 's/:\.,\.,\.:/:.:/g' \
      -e 's/:\.,,:/:.:/g' \
      1KG.chr22.anno.infocol.vcf > 1KG.chr22.anno.infocol.edit.vcf
```

**Comment by Steven-N-Hart** [comment]
Updated the download after running this script.  No one else should hit this issue now.  Thanks!

**Comment by heuermh** [comment]
I believe the first fix is actually unnecessary, rather a bug in htsjdk, see https://github.com/samtools/htsjdk/issues/517.

Then according to the VCF specification, spaces are not allowed in the INFO field, but `'s/ /%20/g'` is too heavy handed, since it replaces spaces in all the documentation strings.
